// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYgr5AFO-tD-Yr6iUqIz5a3s1EvSHOlYI',
    appId: '1:741335584680:web:95878320088d3c412b579d',
    messagingSenderId: '741335584680',
    projectId: 'reuse-mart-53b03',
    authDomain: 'reuse-mart-53b03.firebaseapp.com',
    storageBucket: 'reuse-mart-53b03.firebasestorage.app',
    measurementId: 'G-7RJ3VXFDYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxrhLi8Ws9KzkLFZGZHVw0YzaxE26vqSs',
    appId: '1:741335584680:android:588af80dba00808e2b579d',
    messagingSenderId: '741335584680',
    projectId: 'reuse-mart-53b03',
    storageBucket: 'reuse-mart-53b03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXkJg_MLxpCFlLuH-Mt0_gKuc-UzTa2U',
    appId: '1:741335584680:ios:8246ed4a3a0d889e2b579d',
    messagingSenderId: '741335584680',
    projectId: 'reuse-mart-53b03',
    storageBucket: 'reuse-mart-53b03.firebasestorage.app',
    iosBundleId: 'com.example.reuseMartMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXkJg_MLxpCFlLuH-Mt0_gKuc-UzTa2U',
    appId: '1:741335584680:ios:8246ed4a3a0d889e2b579d',
    messagingSenderId: '741335584680',
    projectId: 'reuse-mart-53b03',
    storageBucket: 'reuse-mart-53b03.firebasestorage.app',
    iosBundleId: 'com.example.reuseMartMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYgr5AFO-tD-Yr6iUqIz5a3s1EvSHOlYI',
    appId: '1:741335584680:web:8921a2f9289661142b579d',
    messagingSenderId: '741335584680',
    projectId: 'reuse-mart-53b03',
    authDomain: 'reuse-mart-53b03.firebaseapp.com',
    storageBucket: 'reuse-mart-53b03.firebasestorage.app',
    measurementId: 'G-CC63QG3SRX',
  );
}
